AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        DEVENV: windows # macos | linux
        BASE_URL: "http://localhost:3000"
        PASTE_TTL: 86400 # keep local Paste for 24hours
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: local
      Cors:
        AllowMethods: "'OPTIONS,POST,GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"
        AllowCredentials: "'false'" # Disable credentials for CORS
        # Add the following line to allow unauthenticated OPTIONS requests
        ApiGatewayManagedCors: "'true'"
  PastebinFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 5
      Architectures:
        - x86_64
      Events:
        GetPaste:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /paste
            Method: get
        GetApiPaste:
          Type: Api
          Properties:
            Path: /paste/api
            Method: get
        GetApiPastes:
          Type: Api
          Properties:
            Path: /paste/api/pastes
            Method: get
          cors:
            Type: Api
            Properties:
              Path: /paste
              Method: options
        CreatePaste:
          Type: Api
          Properties:
            Path: /paste
            Method: post
        CreateApiPaste:
          Type: Api
          Properties:
            Path: /paste/api
            Method: post
        cors:
          Type: Api
          Properties:
            Path: /paste
            Method: options
