- name: Install required Python packages
  apt:
    name:
      - python3-pip
    state: present
  notify: Verify Python version

- name: Install pipenv using pip
  command: pip3 install pipenv --break-system-packages
  notify: Verify pipenv installation
