---
- name: Update Debian Machine
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags:
        - update

    - name: List upgradable packages
      command: apt list --upgradable
      register: upgradable_packages
      changed_when: false
      tags:
        - check

    - name: Print upgradable packages
      debug:
        msg: "{{ upgradable_packages.stdout_lines }}"
      tags:
        - check

    - name: Upgrade all packages
      apt:
        upgrade: dist
      tags:
        - upgrade

    - name: Remove unused packages
      apt:
        autoremove: yes
      tags:
        - cleanup

    - name: Clean up apt cache
      apt:
        autoclean: yes
      tags:
        - cleanup
