# This is a basic workflow to help you get started with Actions

name: openapiv3validation

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!main"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: OpenApi Specification Lint action
        uses: crudo/spectral-action@v6.4.0
        with:
          file_path: openapi.yml
