name: openapiv3validation
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true # temporary should be fixed (2024-06-03)
    steps:
      - uses: actions/checkout@v2

      - name: OpenApi Specification Lint action
        uses: crudo/spectral-action@v6.4.0
        with:
          file_path: openapi.yml
