name: LintJobs
on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Lint openapi file
        uses: crudo/spectral-action
        with:
          file_path: openapi.yml
